# SoundSpot — dnsmasq
interface=uap0
bind-interfaces
dhcp-range=${DHCP_START},${DHCP_END},24h
dhcp-option=3,${SPOT_IP}
dhcp-option=6,${SPOT_IP}
# Redirection portail captif : tout → RPi (desactivated)
## address=/#/${SPOT_IP}
# Cache DNS local
cache-size=300
log-queries
log-dhcp
# Autorise internet immédiatement à la connexion (avant validation portail)
# → le smartphone teste HTTPS avec succès et ne rejette pas le hotspot
dhcp-script=/opt/soundspot/dhcp_trigger.sh
