interface=${IFACE_AP}
ssid=${SPOT_NAME}
hw_mode=g
channel=${WIFI_CHANNEL}
ieee80211n=1
wmm_enabled=1
# Réseau ouvert — opennds gère l'accès via la page d'accueil
auth_algs=1
max_num_sta=30 ## maximum satellites (reduce to 5 or 6 if using internal piz2w)
