GatewayInterface uap0
GatewayAddress ${SPOT_IP}
MaxClients 20
loginOption_key 1
ThemeSpecPath /etc/opennds/theme_soundspot.sh
WalledGardenPort ${SNAPCAST_PORT}
WalledGardenPort ${SNAPCAST_HTTP_PORT}
WalledGardenPort 8111
