interface=${IFACE_AP}
ssid=${SPOT_NAME}
hw_mode=g
channel=${WIFI_CHANNEL}
ieee80211n=1
wmm_enabled=1
# Réseau ouvert — lighttpd gère le portail captif (port 80 intercepté par iptables)
auth_algs=1
max_num_sta=30 ## maximum satellites (reduce to 5 or 6 if using internal piz2w)
