[server]
threads = -1

[stream]
source = pipe:///dev/shm/snapfifo?name=SoundSpot_DJ&mode=read
codec = opus

[stream]
source = pipe:///dev/shm/snapfifo_mic?name=SoundSpot_Mic&mode=read
codec = opus

[http]
enabled = true
port = 1780
doc_root = /usr/share/snapserver/snapweb/